# Generated by Django 4.2.6 on 2023-12-29 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("drone", "0003_dronesettings_created_at_dronesettings_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="DroneImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="drone_images/")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
