# Generated by Django 4.2.6 on 2024-01-24 21:49

import apps.drone.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("drone", "0004_droneimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dronesettings",
            name="canals",
        ),
        migrations.CreateModel(
            name="DroneModelSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("prediction_model", models.CharField(max_length=255)),
                (
                    "servo_canals",
                    models.JSONField(default=apps.drone.models.default_canals),
                ),
                (
                    "brushless_canals",
                    models.JSONField(default=apps.drone.models.default_canals),
                ),
                (
                    "drone_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="drone.dronesettings",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="dronesettings",
            name="selected_drone_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drone_related_settings",
                to="drone.dronemodelsettings",
            ),
        ),
    ]
