# Generated by Django 4.2.6 on 2024-01-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drone", "0007_dronemodelsettings_flight_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dronemodelsettings",
            name="flight_mode",
        ),
        migrations.AddField(
            model_name="dronemodelsettings",
            name="flight_mode_channel",
            field=models.IntegerField(default=7),
        ),
    ]
