# Generated by Django 4.2.6 on 2024-03-10 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("drone", "0008_remove_dronemodelsettings_flight_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dronesettings",
            name="altitude_objective",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="dronesettings",
            name="latitude",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="dronesettings",
            name="longitude",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="dronesettings",
            name="selected_drone_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drone_related_settings",
                to="drone.dronemodelsettings",
            ),
        ),
    ]
