# Generated by Django 4.2.6 on 2024-01-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replay", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="replaysessiondata",
            name="pitch",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="replaysessiondata",
            name="roll",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="replaysessiondata",
            name="yaw",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="replaysession",
            name="end_time",
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name="replaysessiondata",
            name="altitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="replaysessiondata",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="replaysessiondata",
            name="longitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="replaysessiondata",
            name="speed",
            field=models.FloatField(null=True),
        ),
    ]
