# Generated by Django 4.2.6 on 2024-01-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replay", "0002_replaysessiondata_pitch_replaysessiondata_roll_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replaysession",
            name="end_time",
            field=models.DateTimeField(null=True),
        ),
    ]
