# Generated by Django 4.2.6 on 2024-01-19 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("replay", "0004_replaysession_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replaysessiondata",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data",
                to="replay.replaysession",
            ),
        ),
    ]
