# Generated by Django 4.2.6 on 2024-01-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("replay", "0005_alter_replaysessiondata_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="replaysession",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
